export const SOUND_EVENTS = {
    // Combat Status
    BLOODY_HIT: "CORE_HIT",
    CORE_HIT: "CORE_HIT",
    PC_DEATH: "PC_DEATH", // Generic fallback
    PC_DEATH_MASCULINE: "CORE_DEATH_MASCULINE",
    PC_DEATH_FEMININE: "CORE_DEATH_FEMININE",

    PC_PAIN_MASCULINE: "CORE_PAIN_MASCULINE",
    PC_PAIN_FEMININE: "CORE_PAIN_FEMININE",

    CRIT_DECORATION: "CORE_CRIT",
    CORE_CRIT: "CORE_CRIT",
    MISS: "CORE_MISS",

    // Spells
    SPELL_FIRE: "SPELL_FIRE",
    SPELL_ICE: "SPELL_ICE",
    SPELL_LIGHTNING: "SPELL_LIGHTNING",
    SPELL_VOID: "SPELL_VOID",
    SPELL_HEAL: "SPELL_HEAL",
    SPELL_PSYCHIC: "SPELL_PSYCHIC",
    SPELL_ACID: "SPELL_ACID",

    // Weapons / Attacks
    ATTACK_CLAW: "ATTACK_CLAW",
    ATTACK_BITE: "ATTACK_BITE",
    ATTACK_SLAM: "ATTACK_SLAM",

    ATTACK_BOW: "ATTACK_BOW", // Generic
    ATTACK_BOW_FIRE: "ATTACK_BOW_FIRE",
    ATTACK_BOW_HIT: "ATTACK_BOW_HIT",

    ATTACK_CROSSBOW: "ATTACK_CROSSBOW", // Generic
    ATTACK_CROSSBOW_HIT: "ATTACK_CROSSBOW_HIT",

    ATTACK_SLING: "ATTACK_SLING",

    ATTACK_BLUDGEON: "ATTACK_BLUDGEON", // Generic
    ATTACK_BLUDGEON_SWING: "ATTACK_BLUDGEON_SWING",
    ATTACK_BLUDGEON_HIT: "ATTACK_BLUDGEON_HIT",

    ATTACK_DAGGER: "ATTACK_DAGGER", // Generic
    ATTACK_DAGGER_SLASH: "ATTACK_DAGGER_SLASH",
    ATTACK_DAGGER_HIT: "ATTACK_DAGGER_HIT",

    ATTACK_SWORD: "ATTACK_SWORD", // Generic
    ATTACK_SWORD_SLASH: "ATTACK_SWORD_SLASH",
    ATTACK_SWORD_HIT: "ATTACK_SWORD_HIT",

    // Monster Vocals (Pain/Attack)
    MONSTER_UNDEAD: "MONSTER_UNDEAD", // Generic
    MONSTER_ZOMBIE: "MONSTER_ZOMBIE",
    MONSTER_SKELETON: "MONSTER_SKELETON",
    MONSTER_GHOST: "MONSTER_GHOST",

    MONSTER_BEAST: "MONSTER_BEAST",
    MONSTER_INSECT: "MONSTER_INSECT",
    MONSTER_REPTILE: "MONSTER_REPTILE",
    MONSTER_PLANT: "MONSTER_PLANT",

    MONSTER_HUMANOID: "MONSTER_HUMANOID",

    MONSTER_FIEND: "MONSTER_FIEND", // Generic
    MONSTER_FIEND_FERAL: "MONSTER_FIEND_FERAL",
    MONSTER_FIEND_INTELLIGENT: "MONSTER_FIEND_INTELLIGENT",

    MONSTER_GOBLIN: "MONSTER_GOBLIN",
    MONSTER_ORC: "MONSTER_ORC",
    MONSTER_GIANT: "MONSTER_GIANT",
    MONSTER_DRAGON: "MONSTER_DRAGON",
    MONSTER_CONSTRUCT: "MONSTER_CONSTRUCT",
    MONSTER_ELEMENTAL: "MONSTER_ELEMENTAL",

    MONSTER_BEAR: "MONSTER_BEAR",
    MONSTER_WOLF: "MONSTER_WOLF",
    MONSTER_CAT: "MONSTER_CAT",
    MONSTER_BIRD: "MONSTER_BIRD",
    MONSTER_HORSE: "MONSTER_HORSE",

    MONSTER_DEMON: "MONSTER_DEMON",
    MONSTER_ALIEN: "MONSTER_ALIEN",
    MONSTER_ROAR: "MONSTER_ROAR",
    MONSTER_SPIDER: "MONSTER_SPIDER",
    MONSTER_LYCANTHROPE: "MONSTER_LYCANTHROPE",

    // SFX / Elements
    SFX_SLIME: "SFX_SLIME",
    SFX_WIND: "SFX_WIND",
    SFX_WATER: "SFX_WATER",
    SFX_WATER_ENTITY: "SFX_WATER_ENTITY",
    SFX_FIRE: "SFX_FIRE",
    SFX_INSECT: "SFX_INSECT",
    SFX_CHOIR: "SFX_CHOIR",
    SFX_MEOW: "SFX_MEOW",
    SFX_BARK: "SFX_BARK",
    SFX_SQUEAK: "SFX_SQUEAK",
    SFX_CHIME: "SFX_CHIME",
    SFX_ARMOR_CLANK: "SFX_ARMOR_CLANK",
    SFX_BOW: "ATTACK_BOW",    // Daggerheart Mechanics
    DAGGERHEART_HOPE: "DAGGERHEART_HOPE",
    DAGGERHEART_FEAR: "DAGGERHEART_FEAR",
    DAGGERHEART_HOPE_USE: "DAGGERHEART_HOPE_USE",
    DAGGERHEART_FEAR_USE: "DAGGERHEART_FEAR_USE",
    DAGGERHEART_STRESS: "DAGGERHEART_STRESS",
    DAGGERHEART_STRESS_CLEAR: "DAGGERHEART_STRESS_CLEAR",
    DAGGERHEART_ARMOR_USE: "DAGGERHEART_ARMOR_USE",
    DAGGERHEART_ARMOR_REPAIR: "DAGGERHEART_ARMOR_REPAIR",

    // Daggerheart Roll Outcomes (Granular)
    DAGGERHEART_CRIT: "DAGGERHEART_CRIT", // Doubles
    DAGGERHEART_SUCCESS_WITH_HOPE: "DAGGERHEART_SUCCESS_WITH_HOPE",
    DAGGERHEART_SUCCESS_WITH_FEAR: "DAGGERHEART_SUCCESS_WITH_FEAR",
    DAGGERHEART_FAIL_WITH_HOPE: "DAGGERHEART_FAIL_WITH_HOPE",
    DAGGERHEART_FAIL_WITH_FEAR: "DAGGERHEART_FAIL_WITH_FEAR", // Fumble

    // Daggerheart Roll Outcomes (Legacy - Hope/Fear dominance only)
    DAGGERHEART_ROLL_HOPE: "DAGGERHEART_ROLL_HOPE",
    DAGGERHEART_ROLL_FEAR: "DAGGERHEART_ROLL_FEAR",

    // Default
    WHOOSH: "CORE_WHOOSH"
};
