export const SOUND_EVENTS = {
    // Combat Status
    BLOODY_HIT: "CORE_HIT",
    CORE_HIT: "CORE_HIT",
    PC_DEATH: "PC_DEATH", // Generic fallback
    PC_DEATH_MASCULINE: "CORE_DEATH_MASCULINE",
    PC_DEATH_FEMININE: "CORE_DEATH_FEMININE",

    CORE_MONSTER_PAIN: "CORE_MONSTER_PAIN",
    CORE_MONSTER_DEATH: "CORE_MONSTER_DEATH",

    PC_PAIN_MASCULINE: "CORE_PAIN_MASCULINE",
    PC_PAIN_FEMININE: "CORE_PAIN_FEMININE",

    CRIT_DECORATION: "CORE_CRIT",  // @legacy — alias kept for back-compat; v3: deprecate
    CORE_CRIT: "CORE_CRIT",
    MISS: "CORE_MISS",               // @legacy — alias kept for back-compat; v3: deprecate

    // Category-Aware Hit/Miss (auto-selected by attack type)
    CORE_HIT_RANGED: "CORE_HIT_RANGED",
    CORE_HIT_MAGIC: "CORE_HIT_MAGIC",
    CORE_MISS_RANGED: "CORE_MISS_RANGED",
    CORE_MISS_MAGIC: "CORE_MISS_MAGIC",

    // Spells
    SPELL_FIRE: "SPELL_FIRE",
    SPELL_ICE: "SPELL_ICE",
    SPELL_LIGHTNING: "SPELL_LIGHTNING",
    SPELL_VOID: "SPELL_VOID",
    SPELL_HEAL: "SPELL_HEAL",
    SPELL_PSYCHIC: "SPELL_PSYCHIC",
    SPELL_ACID: "SPELL_ACID",

    // Weapons / Attacks
    ATTACK_CLAW: "ATTACK_CLAW",
    ATTACK_BITE: "ATTACK_BITE",
    ATTACK_SLAM: "ATTACK_SLAM",

    ATTACK_BOW: "ATTACK_BOW", // Generic
    ATTACK_BOW_FIRE: "ATTACK_BOW_FIRE",
    ATTACK_BOW_HIT: "ATTACK_BOW_HIT",

    ATTACK_CROSSBOW: "ATTACK_CROSSBOW", // Generic
    ATTACK_CROSSBOW_HIT: "ATTACK_CROSSBOW_HIT",

    ATTACK_SLING: "ATTACK_SLING",

    ATTACK_BLUDGEON: "ATTACK_BLUDGEON", // Generic
    ATTACK_BLUDGEON_SWING: "ATTACK_BLUDGEON_SWING",
    ATTACK_BLUDGEON_HIT: "ATTACK_BLUDGEON_HIT",

    ATTACK_DAGGER: "ATTACK_DAGGER", // Generic
    ATTACK_DAGGER_SLASH: "ATTACK_DAGGER_SLASH",
    ATTACK_DAGGER_HIT: "ATTACK_DAGGER_HIT",

    ATTACK_SWORD: "ATTACK_SWORD", // Generic
    ATTACK_SWORD_SLASH: "ATTACK_SWORD_SLASH",
    ATTACK_SWORD_HIT: "ATTACK_SWORD_HIT",

    // Monster Vocals (Pain/Attack)
    MONSTER_UNDEAD: "MONSTER_UNDEAD", // Generic
    MONSTER_ZOMBIE: "MONSTER_ZOMBIE",
    MONSTER_SKELETON: "MONSTER_SKELETON",
    MONSTER_GHOST: "MONSTER_GHOST",

    MONSTER_BEAST: "MONSTER_BEAST",
    MONSTER_INSECT: "MONSTER_INSECT",
    MONSTER_REPTILE: "MONSTER_REPTILE",
    MONSTER_PLANT: "MONSTER_PLANT",

    MONSTER_HUMANOID: "MONSTER_HUMANOID",

    MONSTER_FIEND: "MONSTER_FIEND", // Generic
    MONSTER_FIEND_FERAL: "MONSTER_FIEND_FERAL",
    MONSTER_FIEND_INTELLIGENT: "MONSTER_FIEND_INTELLIGENT",

    MONSTER_GOBLIN: "MONSTER_GOBLIN",
    MONSTER_ORC: "MONSTER_ORC",
    MONSTER_GIANT: "MONSTER_GIANT",
    MONSTER_DRAGON: "MONSTER_DRAGON",
    MONSTER_CONSTRUCT: "MONSTER_CONSTRUCT",
    MONSTER_ELEMENTAL: "MONSTER_ELEMENTAL",

    MONSTER_BEAR: "MONSTER_BEAR",
    MONSTER_WOLF: "MONSTER_WOLF",
    MONSTER_CAT: "MONSTER_CAT",
    MONSTER_BIRD: "MONSTER_BIRD",
    MONSTER_HORSE: "MONSTER_HORSE",

    MONSTER_DEMON: "MONSTER_DEMON",
    MONSTER_ALIEN: "MONSTER_ALIEN",
    MONSTER_ROAR: "MONSTER_ROAR",
    MONSTER_SPIDER: "MONSTER_SPIDER",
    MONSTER_LYCANTHROPE: "MONSTER_LYCANTHROPE",

    // SFX / Elements
    SFX_SLIME: "SFX_SLIME",
    SFX_WIND: "SFX_WIND",
    SFX_WATER: "SFX_WATER",
    SFX_WATER_ENTITY: "SFX_WATER_ENTITY",
    SFX_FIRE: "SFX_FIRE",
    SFX_INSECT: "SFX_INSECT",
    SFX_CHOIR: "SFX_CHOIR",
    SFX_MEOW: "SFX_MEOW",
    SFX_BARK: "SFX_BARK",
    SFX_SQUEAK: "SFX_SQUEAK",
    SFX_CHIME: "SFX_CHIME",
    SFX_ARMOR_CLANK: "SFX_ARMOR_CLANK",
    SFX_BOW: "ATTACK_BOW",    // Daggerheart Mechanics
    DAGGERHEART_HOPE: "DAGGERHEART_HOPE",
    DAGGERHEART_FEAR: "DAGGERHEART_FEAR",
    DAGGERHEART_HOPE_USE: "DAGGERHEART_HOPE_USE",
    DAGGERHEART_FEAR_USE: "DAGGERHEART_FEAR_USE",
    DAGGERHEART_STRESS: "DAGGERHEART_STRESS",
    DAGGERHEART_STRESS_CLEAR: "DAGGERHEART_STRESS_CLEAR",
    DAGGERHEART_ARMOR_USE: "DAGGERHEART_ARMOR_USE",
    DAGGERHEART_ARMOR_REPAIR: "DAGGERHEART_ARMOR_REPAIR",

    // Daggerheart Roll Outcomes (Granular)
    DAGGERHEART_CRIT: "DAGGERHEART_CRIT", // Doubles
    DAGGERHEART_SUCCESS_WITH_HOPE: "DAGGERHEART_SUCCESS_WITH_HOPE",
    DAGGERHEART_SUCCESS_WITH_FEAR: "DAGGERHEART_SUCCESS_WITH_FEAR",
    DAGGERHEART_FAIL_WITH_HOPE: "DAGGERHEART_FAIL_WITH_HOPE",
    DAGGERHEART_FAIL_WITH_FEAR: "DAGGERHEART_FAIL_WITH_FEAR", // Fumble

    // Daggerheart Roll Outcomes (Legacy - Hope/Fear dominance only)
    DAGGERHEART_ROLL_HOPE: "DAGGERHEART_ROLL_HOPE",
    DAGGERHEART_ROLL_FEAR: "DAGGERHEART_ROLL_FEAR",

    // Default — fires on attack swing (BEFORE hit/miss result is known).
    // Falls back from CORE_MELEE and CORE_RANGED when no specific weapon sound is mapped.
    // @v3-rename: CORE_WHOOSH → CORE_ATTACK_SWING (see SOUND_KEY_REFACTOR_v3.md)

    // ─── v3 Semantic Aliases ─────────────────────────────────────────────────
    // Values intentionally match legacy strings — user configs remain valid.
    // v4: string values will be updated + migration bridge added.

    // ASK — declare action (before roll)
    ASK_GENERIC_MELEE: "CORE_MELEE",   // category fallback for any unmatched melee ask
    ASK_GENERIC_RANGED: "CORE_RANGED",  // category fallback for any unmatched ranged ask
    ASK_GENERIC_MAGIC: "CORE_MAGIC",   // category fallback for any unmatched spell/domain
    ASK_SWORD: "ATTACK_SWORD",
    ASK_DAGGER: "ATTACK_DAGGER",
    ASK_BLUDGEON: "ATTACK_BLUDGEON",
    ASK_BOW: "ATTACK_BOW",
    ASK_CROSSBOW: "ATTACK_CROSSBOW",
    ASK_SLING: "ATTACK_SLING",
    ASK_CLAW: "ATTACK_CLAW",
    ASK_BITE: "ATTACK_BITE",
    ASK_SLAM: "ATTACK_SLAM",
    ASK_SPELL_FIRE: "SPELL_FIRE",
    ASK_SPELL_ICE: "SPELL_ICE",
    ASK_SPELL_LIGHTNING: "SPELL_LIGHTNING",
    ASK_SPELL_VOID: "SPELL_VOID",
    ASK_SPELL_HEAL: "SPELL_HEAL",
    ASK_SPELL_PSYCHIC: "SPELL_PSYCHIC",
    ASK_SPELL_ACID: "SPELL_ACID",

    // ANSWER — roll result
    ANSWER_HIT: "CORE_HIT",
    ANSWER_HIT_RANGED: "CORE_HIT_RANGED",
    ANSWER_HIT_MAGIC: "CORE_HIT_MAGIC",
    ANSWER_MISS: "CORE_MISS",
    ANSWER_MISS_RANGED: "CORE_MISS_RANGED",
    ANSWER_MISS_MAGIC: "CORE_MISS_MAGIC",
    ANSWER_CRIT_HIT: "CORE_CRIT",         // combat weapon crit — NOT a roll stinger
    ANSWER_ROLL_CRIT: "DAGGERHEART_CRIT",  // roll-outcome stinger (combat + social)
    ANSWER_SUCCESS_HOPE: "DAGGERHEART_SUCCESS_WITH_HOPE",
    ANSWER_SUCCESS_FEAR: "DAGGERHEART_SUCCESS_WITH_FEAR",
    ANSWER_FAIL_FEAR: "DAGGERHEART_FAIL_WITH_FEAR",

    // VOCAL — creature response (pain / death)
    VOCAL_GENERIC_PAIN: "CORE_MONSTER_PAIN",
    VOCAL_GENERIC_DEATH: "CORE_MONSTER_DEATH",
    VOCAL_PC_PAIN_MASCULINE: "CORE_PAIN_MASCULINE",
    VOCAL_PC_PAIN_FEMININE: "CORE_PAIN_FEMININE",
    VOCAL_PC_DEATH_MASCULINE: "CORE_DEATH_MASCULINE",
    VOCAL_PC_DEATH_FEMININE: "CORE_DEATH_FEMININE",
    VOCAL_PC_DEATH: "PC_DEATH",
    VOCAL_BEAR: "MONSTER_BEAR",
    VOCAL_WOLF: "MONSTER_WOLF",
    VOCAL_DRAGON: "MONSTER_DRAGON",
    VOCAL_UNDEAD: "MONSTER_UNDEAD",
    VOCAL_ZOMBIE: "MONSTER_ZOMBIE",
    VOCAL_SKELETON: "MONSTER_SKELETON",
    VOCAL_GHOST: "MONSTER_GHOST",
    VOCAL_GOBLIN: "MONSTER_GOBLIN",
    VOCAL_ORC: "MONSTER_ORC",
    VOCAL_GIANT: "MONSTER_GIANT",
    VOCAL_CONSTRUCT: "MONSTER_CONSTRUCT",
    VOCAL_FIEND: "MONSTER_FIEND",
    VOCAL_HUMANOID: "MONSTER_HUMANOID",
    VOCAL_BEAST: "MONSTER_BEAST",
    VOCAL_ELEMENTAL: "MONSTER_ELEMENTAL",
    VOCAL_ELEMENTAL_FIRE: "SFX_FIRE",  // elemental pain response
    VOCAL_INSECT: "MONSTER_INSECT",
    VOCAL_SPIDER: "MONSTER_SPIDER",
    VOCAL_LYCANTHROPE: "MONSTER_LYCANTHROPE",
    VOCAL_GENERIC_DEATH: "CORE_MONSTER_DEATH",  // NPC/adversary death fallback
    VOCAL_GENERIC_PAIN: "CORE_MONSTER_PAIN",    // NPC/adversary pain fallback

    // ─── Legacy aliases (@v2) ─────────────────────────────────────────────────
    // @legacy: kept for backward compat and as chain terminal until default
    // preset migrates CORE_MELEE/CORE_RANGED bindings away from CORE_WHOOSH.
    // v4: remove once preset data uses ASK_GENERIC_MELEE/RANGED directly.
    WHOOSH: "CORE_WHOOSH",
    CRIT_DECORATION: "CORE_CRIT",
    BLOODY_HIT: "CORE_HIT",
    MISS: "CORE_MISS",
};
